version: '2'
services:

  busybox:
    extends:
      file: common-compose.yml
      service: busybox
    volumes:
    - ./src:/var/www
    depends_on:
    - nginx
    - php-fpm
    - mongo
    - mysql
    - memcached

  nginx:
    extends:
      file: common-compose.yml
      service: nginx
    depends_on:
    - php-fpm
    - mysql

  php-fpm:
    extends:
      file: common-compose.yml
      service: php-fpm
    depends_on:
    - mysql
    - mongo
    - memcached

  phpmyadmin:
    extends:
      file: common-compose.yml
      service: phpmyadmin
    links:
      - mysql:db
    depends_on:
    - mysql

  mongo:
    extends:
      file: common-compose.yml
      service: mongo

  mysql:
    extends:
      file: common-compose.yml
      service: mysql

  memcached:
    extends:
      file: common-compose.yml
      service: memcached
